#!/usr/bin/bash
# This file is generated by shirodeb with ingredients support
# Have a nice day ^_^
# By the way, DO NOT edit this file if you don't know what you're doing!

$RUNTIME_EXPORT

$EXEC $EXEC_COMMAND "$@"
